regne_hostil_club_homepage:
    pattern:  /
    defaults: { _controller: RegneHostilClubBundle:Default:index }

regne_hostil_club_show_noticia:
    pattern: /noticia/{id}
    defaults: { _controller: RegneHostilClubBundle:Default:showNoticia}

regne_hostil_club_change_language:
    pattern: /lang/{lang}
    defaults: { _controller: RegneHostilClubBundle:Default:changeLanguage}

regne_hostil_club_about_us:
    pattern: /about
    defaults: { _controller: RegneHostilClubBundle:Default:about }

regne_hostil_club_contact:
    pattern: /contact
    defaults: { _controller: RegneHostilClubBundle:Default:contact }

regne_hostil_club_gallery:
    pattern: /gallery
    defaults: { _controller: RegneHostilClubBundle:Default:galleryIndex }

regne_hostil_club_show_album:
    pattern: /gallery/{album}
    defaults: { _controller: RegneHostilClubBundle:Default:showAlbum }