regne_hostil_club_homepage:
    pattern:  /
    defaults: { _controller: RegneHostilClubBundle:Default:index }

regne_hostil_club_show_noticia:
    pattern: /noticia/{id}
    defaults: { _controller: RegneHostilClubBundle:Default:showNoticia}

regne_hostil_club_change_language:
    pattern: /lang/{lang}
    defaults: { _controller: RegneHostilClubBundle:Default:changeLanguage}

regne_hostil_club_about_us:
    pattern: /about
    defaults: { _controller: RegneHostilClubBundle:Default:about }

regne_hostil_club_contact:
    pattern: /contact
    defaults: { _controller: RegneHostilClubBundle:Default:contact }

regne_hostil_club_gallery:
    pattern: /gallery
    defaults: { _controller: RegneHostilClubBundle:Default:galleryIndex }

regne_hostil_club_show_album:
    pattern: /gallery/{album}
    defaults: { _controller: RegneHostilClubBundle:Default:showAlbum }

regne_hostil_club_admin:
    pattern: /admin
    defaults: { _controller: RegneHostilClubBundle:Admin:index }

regne_hostil_club_admin_create_noticia:
    pattern: /admin/noticies/new
    defaults: { _controller: RegneHostilClubBundle:Admin:createNoticia }

regne_hostil_club_admin_noticies:
    pattern: /admin/noticies
    defaults: { _controller: RegneHostilClubBundle:Admin:llistarNoticies }

regne_hostil_club_admin_edit_noticia:
    pattern: /admin/noticia/{id}
    defaults: { _controller: RegneHostilClubBundle:Admin:editNoticia }

regne_hostil_club_admin_delete_noticia:
    pattern: /admin/noticia/{id}/delete
    defaults: { _controller: RegneHostilClubBundle:Admin:deleteNoticia }

regne_hostil_club_admin_quotes:
    pattern: /admin/quotes
    defaults: { _controller: RegneHostilClubBundle:Admin:listQuotes }

regne_hostil_club_admin_create_quote:
    pattern: /admin/quotes/new
    defaults: { _controller: RegneHostilClubBundle:Admin:createQuote }

regne_hostil_club_admin_edit_quote:
    pattern: /admin/quote/{id}
    defaults: { _controller: RegneHostilClubBundle:Admin:editQuote }

regne_hostil_club_admin_delete_quote:
    pattern: /admin/quote/{id}/delete
    defaults: { _controller: RegneHostilClubBundle:Admin:deleteQuote }